#!/bin/bash

# Defined backup directory found in root
backup_dir="/backup"

# Create backup directory if it doesn't exist
mkdir -p "$backup_dir"

# Define directories to backup
directories=("/etc" "/home" "/root" "/var/log" "/usr/local/bin")

# Backup each directory
for dir in "${directories[@]}"; do
    echo "Backing up $dir"
    tar -czf "$backup_dir/$(basename $dir).tar.gz" "$dir"
done

echo "Backup complete."
